package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.TableEntity;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TableEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TABLE_ENTITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TABLE_ENTITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    int insert(TableEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TABLE_ENTITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    TableEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TABLE_ENTITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    List<TableEntity> selectAll();

    List<TableEntity> selectAllByRestaurantId(Integer restaurant_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TABLE_ENTITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    int updateByPrimaryKey(TableEntity record);
}