package lt.vu.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.SURNAME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.RESERVATION_TIME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    private String reservationTime;


    /** custom field to map many to many relation with customer*/
    private List<TableEntity> tableEntities = new ArrayList<>();


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @return the value of PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @param name the value for PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.SURNAME
     *
     * @return the value of PUBLIC.CUSTOMER.SURNAME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.SURNAME
     *
     * @param surname the value for PUBLIC.CUSTOMER.SURNAME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.RESERVATION_TIME
     *
     * @return the value of PUBLIC.CUSTOMER.RESERVATION_TIME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public String getReservationTime() {
        return reservationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.RESERVATION_TIME
     *
     * @param reservationTime the value for PUBLIC.CUSTOMER.RESERVATION_TIME
     *
     * @mbg.generated Sat Mar 14 12:26:15 EET 2020
     */
    public void setReservationTime(String reservationTime) {
        this.reservationTime = reservationTime;
    }
}