package lt.vu.mybatis.model;

public class TableCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TABLE_CUSTOMER.CUSTOMERS_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    private Integer customersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TABLE_CUSTOMER.TABLES_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    private Integer tablesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TABLE_CUSTOMER.CUSTOMERS_ID
     *
     * @return the value of PUBLIC.TABLE_CUSTOMER.CUSTOMERS_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public Integer getCustomersId() {
        return customersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TABLE_CUSTOMER.CUSTOMERS_ID
     *
     * @param customersId the value for PUBLIC.TABLE_CUSTOMER.CUSTOMERS_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public void setCustomersId(Integer customersId) {
        this.customersId = customersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TABLE_CUSTOMER.TABLES_ID
     *
     * @return the value of PUBLIC.TABLE_CUSTOMER.TABLES_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public Integer getTablesId() {
        return tablesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TABLE_CUSTOMER.TABLES_ID
     *
     * @param tablesId the value for PUBLIC.TABLE_CUSTOMER.TABLES_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public void setTablesId(Integer tablesId) {
        this.tablesId = tablesId;
    }
}