package lt.vu.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class TableEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TABLE_ENTITY.ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TABLE_ENTITY.RESTAURANT_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    private Integer restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TABLE_ENTITY.CAPACITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    private Integer capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TABLE_ENTITY.DESCRIPTION
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TABLE_ENTITY.ID
     *
     * @return the value of PUBLIC.TABLE_ENTITY.ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */

    /** custom field to map many to many relation with customer*/
    private List<Customer> customers = new ArrayList<>();

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TABLE_ENTITY.ID
     *
     * @param id the value for PUBLIC.TABLE_ENTITY.ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TABLE_ENTITY.RESTAURANT_ID
     *
     * @return the value of PUBLIC.TABLE_ENTITY.RESTAURANT_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TABLE_ENTITY.RESTAURANT_ID
     *
     * @param restaurantId the value for PUBLIC.TABLE_ENTITY.RESTAURANT_ID
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TABLE_ENTITY.CAPACITY
     *
     * @return the value of PUBLIC.TABLE_ENTITY.CAPACITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TABLE_ENTITY.CAPACITY
     *
     * @param capacity the value for PUBLIC.TABLE_ENTITY.CAPACITY
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TABLE_ENTITY.DESCRIPTION
     *
     * @return the value of PUBLIC.TABLE_ENTITY.DESCRIPTION
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TABLE_ENTITY.DESCRIPTION
     *
     * @param description the value for PUBLIC.TABLE_ENTITY.DESCRIPTION
     *
     * @mbg.generated Thu Mar 12 11:58:57 EET 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }
}